#
# consensus_taxonomy.R
#
# Written by Daniel Nimptsch
#

# Consensus taxonomy ----------------------------------------------------------------------------------------------

# Main function to generate a consensus taxonomy table out of the final_table
# The final_table needs to have many hits for each query seq in order to do the
# calculations for consensus taxonomy.
# The consensus taxonomy is determined by a generated tree of the taxonomic ranks
# of the query seq. Then the branch with the maximal accumulated bitscore is the consensus
get_consensus_taxonomy <- function(final_table, dataset_path) {

  # Library
  require(data.tree)
  require(progress)

  # Progress
  message("Get consensus taxonomy, progress in percent:")
  final_percent <- 0
  pb <- progress_bar$new(total = 100)

  # Create the consensus taxonomy table
  # row number equals the seq number
  seq_ids <- unique(final_table$seq_ID)
  consensus_taxonomy_table <- final_table[1:length(seq_ids), ]
  consensus_taxonomy_table$seq_ID <- seq_ids
  colnames(consensus_taxonomy_table)[4] <- "consensus_taxonomy"
  consensus_taxonomy_table[, 2:ncol(consensus_taxonomy_table)] <- NA
  consensus_taxonomy_table <- as_tibble(consensus_taxonomy_table)

  # Show progress bar with 0 percent
  pb$tick(0)
  
  # Tree output file
  tree_file <- file.path(dataset_path, "consensus_taxonomy_trees.txt")

  # Write the tree to file
  write("--- Consensus taxonomy tree for the seq_ids from the blastout-file",
    file = tree_file, append = FALSE
  )
  write("--- Colums: tree, bitscore", file = tree_file, append = TRUE)
  write("--- Generated by blastout_to_table.R, Daniel Nimptsch",
    file = tree_file, append = TRUE
  )
  write("", file = tree_file, append = TRUE)

  # For all the individual query seqs
  for (i in 1:length(seq_ids)) {

    # Generate a taxa table with the lineage and bitscore column
    taxa <- final_table$sci_names[final_table$seq_ID == seq_ids[i]]
    taxa <- cbind(taxa, final_table$bitscore[final_table$seq_ID == seq_ids[i]])
    colnames(taxa) <- c("pathString", "bitscore")
    taxa <- transform(taxa, bitscore = as.numeric(bitscore))
    taxa <- as_tibble(taxa)
    taxa$pathString <- str_glue("Origin;{taxa$pathString}")

    # Copy all the information from the final_table corresponding to the seq number
    taxa_info <- final_table[final_table$seq_ID == seq_ids[i], ]

    # Sum up the bitscore for the different hits with same lineage
    for (y in 1:length(unique(taxa$pathString))) {
      ind <- which(taxa$pathString == unique(taxa$pathString)[y])
      total_bitscore <- sum(taxa$bitscore[ind])
      taxa$bitscore[ind] <- total_bitscore
    }

    # Generate a hierarchical tree out of the taxa table
    tree <- FromDataFrameTable(taxa, pathName = "pathString", pathDelimiter = ";")

    # Aggregate the bitscore values in the tree from the leaves up to the root
    tree$Do(
      function(node) {
        node$bitscore <- Aggregate(node, attribute = "bitscore", aggFun = sum)
      },
      traversal = "pre-order"
    )

    # Sort the tree with the bitscore values in descending order
    Sort(tree, "bitscore", decreasing = TRUE, recursive = TRUE)

    # Write the tree to file
    write(seq_ids[i], file = tree_file, append = TRUE)
    save_tree <- ToDataFrameTree(tree, "bitscore")
    write.table(save_tree,
      file = tree_file,
      append = TRUE, sep = "\t",
      col.names = FALSE, row.names = FALSE, quote = FALSE
    )
    write("", file = tree_file, append = TRUE)

    # The consensus taxonomy will be the first branch
    # Due to the sorting the first branch will contain the lineage with the
    # highest accumulated bitscore value
    lineage <- tree$Get(
      "name",
      pruneFun = function(node) {
        node$position == 1
      }
    )

    # Remove the root
    lineage <- lineage[-1]

    consensus_taxonomy_info_ind <- which(taxa_info$sci_names == paste(lineage, collapse = ";"))[1]
    consensus_taxonomy_table[i, c(2, 3)] <- taxa_info[consensus_taxonomy_info_ind, c(2, 3)]
    consensus_taxonomy_table[i, c(5:11)] <- taxa_info[consensus_taxonomy_info_ind, c(5:11)]
    consensus_taxonomy_table$consensus_taxonomy[i] <- paste(lineage, collapse = ";")

    percent <- round(i / length(seq_ids) * 100)
    if (percent > final_percent) {
      final_percent <- percent
      pb$tick()
    }
  }

  detach("package:data.tree", unload = TRUE)
  detach("package:progress", unload = TRUE)

  return(as.data.frame(consensus_taxonomy_table))
}
